### ISSUE TITLE
ros-operator needs to add the Rancher cacert to the machine registration

### ISSUE THREAD

**Issue by kkaempf** [rancher-sandbox/os2#1]
### Problem statement

ros-operator currently returns

```
rancheros:
    install:
        registrationUrl: https://172.17.0.2/v1-rancheros/registration/g75mqpnrlrrgqqbf9cxwzw2b75bt5xngdv9pljprdd7vp4cqd27hjx
```

from the `registrationUrl`. However, `ros-installer` will barf at this since it's "signed with an unknown authority".

Adding the Rancher cacert (from 'left pane' -> 'global settings' -> 'Advanced settings' -> 'Show cacerts') as in

```
rancheros:
    install:
        registrationUrl: https://172.17.0.2/v1-rancheros/registration/g75mqpnrlrrgqqbf9cxwzw2b75bt5xngdv9pljprdd7vp4cqd27hjx
        registrationCaCert: |
          -----BEGIN CERTIFICATE-----
          MIIBpzCCAU2gAwIBAgIBADAKBggqhkjOPQQDAjA7MRwwGgYDVQQKExNkeW5hbWlj
          bGlzdGVuZXItb3JnMRswGQYDVQQDExJkeW5hbWljbGlzdGVuZXItY2EwHhcNMjIw
          MTI1MDgxMjAxWhcNMzIwMTIzMDgxMjAxWjA7MRwwGgYDVQQKExNkeW5hbWljbGlz
          dGVuZXItb3JnMRswGQYDVQQDExJkeW5hbWljbGlzdGVuZXItY2EwWTATBgcqhkjO
          PQIBBggqhkjOPQMBBwNCAAS8ac2BZIHiLMvAasGldNGLvPoxiNLeJgJdn3zEi605
          DKtPVeO9Wq3BY0lKZ0Lz0hEo03POVlJs0ieQjTH5c+1lo0IwQDAOBgNVHQ8BAf8E
          BAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUtB+RIFNNC9JZWcvFJZy2
          AnNILRYwCgYIKoZIzj0EAwIDSAAwRQIgUdk6jxLGX8/AUSS9TiMnlT4sqVksXrWK
          B8gjIV8k9fkCIQDIuV1iRmHzeGLFuFgpkmrtxNQwrxpKhMcs/ZYrDXkW9w==
          -----END CERTIFICATE-----
```

fixes this problem.

### Expected result

Pulling data from the registrationUrl (with `wget`, before building an installation image) should include the cacert in the yaml.

**Comment by agracey** [comment]
Is this the case even when the rancher being used does have a valid cert from let's encrypt?

**Comment by kkaempf** [comment]
Well, Rancher standard install comes with a self-signed cert.
It's a simple fix and adding the public cert shouldn't compromise security.
It might be that a cert-signed-by-upstream-authority wouldn't need this change, but it currently breaks all Rancher standard installs.
