### ISSUE TITLE
Request write access to GitHub rancher/os2

### ISSUE THREAD

**Issue by pgonin** [rancher-sandbox/os2#10]
@kkaempf  @mudler create a request on https://github.com/rancherlabs/eio/issues

**Comment by pgonin** [comment]
just copy https://github.com/rancherlabs/eio/issues/803

**Comment by mudler** [comment]
Getting a 404 on that repo here

**Comment by kkaempf** [comment]
Same for me :-(

**Comment by pgonin** [comment]
Ah right
Working on it
Who should have access too ?

**Comment by kkaempf** [comment]
@bk201 comes to mind.
