### ISSUE TITLE
ros-installer calls non-existing cos-install

### ISSUE THREAD

**Issue by kkaempf** [rancher-sandbox/os2#11]
At https://github.com/rancher-sandbox/os2/blob/391ea8a56549f93839373e0b1ba87204ecb72e3f/pkg/install/install.go#L110

**Comment by mudler** [comment]
This is caused by https://github.com/rancher-sandbox/os2/issues/16, as we are not yet aligned with cOS master and we weren't pinning packer templates previously. Closing it
