### ISSUE TITLE
Enable time sync daemon

### ISSUE THREAD

**Issue by Itxaka** [rancher-sandbox/os2#132]
If your system has the wrong time, it will start failing in certificates, and other stuff. We currently have nothing in place to sync time :o

Create a chronyd package? or just make it part of the distro/base?

**Comment by Itxaka** [comment]
That is awesome news, so we only need to enable it as part of either cos, or the base/distro package I guess? Niiice

**Comment by kkaempf** [comment]
I can add it to the [systemd presets](https://build.opensuse.org/package/show/home:kwk:elemental/systemd-presets-branding-RancherOS2).
But it won't help derivatives (which might not have systemd-timesyncd 😮 )
Not sure what the best place is 🤔

**Comment by mudler** [comment]
A better place for it should be in its framework cloud-config file, where we enable systemd services,e.g. like so (untested):

```
name: "Default config"
stages:
   initramfs:
     - name: "Default systemd config"
       if: '[ -e "/sbin/systemctl" ] || [ -e "/usr/bin/systemctl" ] || [ -e "/usr/sbin/systemctl" ] || [ -e "/usr/bin/systemctl" ]'
       systemctl:
        enable:
        - multi-user.target
        - getty@tty1
        - iscsid
        - systemd-timesyncd
        - sshd
        mask:
        - purge-kernels
``
