### ISSUE TITLE
automatic CDROM ejection

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/os2#31]
Booting ISO should be ejected on shutdown if we set it from a config file option.

This is helpful in scenarios where automated installation are performed and hypervisor are not unmounting the iso after first installation.

Systemd seems supports this, a script can be placed in `/usr/lib/systemd/system-shutdown/name.shutdown` to execute commands during shutdown. I'm not sure if it is possible to hook cdrom ejection, but I believe so, otherwise we have to back off on some custom logic in the initrd. It worth trying with systemd first.

Something among the lines of:
```bash
#!/bin/bash
cd=$(lsblk | grep COS_LIVE | cut -d ' ' -f1)
eject -T /dev/$cd 
```

or a service, like:

```
[Unit]
Description=Eject the DVD
Before=final.target
After=shutdown.target
DefaultDependencies=no

[Service]
Type=oneshot
ExecStart=/usr/bin/eject -m
StandardInput=tty-force
StandardOutput=inherit
StandardError=inherit

[Install]
WantedBy=shutdown.target
```

Either way this have to be dynamic. We don't want always to eject the CDROM as it might not fit in other scenarios (where the CDROM might be used to actually boot a full system, without anything being installed locally) and might break other flows which we are not aware yet. 

We can think about enabling automatically this feature afterwards.

**Comment by jsundqvist** [comment]
Hi, in k3OS there is a `fallback_mode=install` which only runs the installer if there is nothing installed on disk.

This would be preferred for my use case since I have a VPS where I don't have direct access to mount ISO or change boot order. All that needs to be handled by the providers support staff over email.
