### ISSUE TITLE
Hostname is changed upon each reboot

### ISSUE THREAD

**Issue by ldevulder** [rancher-sandbox/os2#35]
After installation I set my hostname to `ros-node-02` and configured a K3s cluster on it with rancherd/Rancher. All was fine but after a reboot the hostname has been changed to something like `rancher-XXXXX`. I tried to reset the hostname but same issue after a reboot.
I'm able to reproduce this every time.

I have a DHCP/DNS server that fix the IP address, so it's not an IP change upon each reboot. I attached journalctl logs on this issue.
[journalctl.log.gz](https://github.com/rancher-sandbox/os2/files/8176206/journalctl.log.gz)

**Comment by mudler** [comment]
How do you set up the hostname?

**Comment by ldevulder** [comment]
> How do you set up the hostname?

I used `hostnamectl set-hostname <hostname>`, and I checked that the correct hostname was set in `/etc/HOSTNAME`

**Comment by mudler** [comment]
> > How do you set up the hostname?
> 
> I used `hostnamectl set-hostname <hostname>`, and I checked that the correct hostname was set in `/etc/HOSTNAME`

That's not the proper way in cOS derivative. any customization is done via cloud-init. See https://rancher-sandbox.github.io/cos-toolkit-docs/docs/customizing/runtime_persistent_changes/

**Comment by mudler** [comment]
> But cloud-init only runs once during install ? A later call to `hostnamectl` shouldn't conflict with cloud-init ?!

No, it is stored in the system /oem after installation. So it persists in the system

**Comment by mudler** [comment]
about how to handle them from kubernetes, we have a follow-up story: https://github.com/rancher-sandbox/cOS-toolkit/issues/749

**Comment by kkaempf** [comment]
Setting a persistant hostname via cloud-init should be exception, not the rule. Maybe it shiuld be even discouraged.

Imagine an edge scenario with hundreds or thousands of clients, all identical hardware, all being deployed from the same machineRegistration crd in k8s. They will all consume the same cloud-init values.

**Comment by mudler** [comment]
> Setting a persistant hostname via cloud-init should be exception, not the rule. Maybe it should be even discouraged.
> 
> Imagine an edge scenario with hundreds or thousands of clients, all identical hardware, all being deployed from the same machineRegistration crd in k8s. They will all consume the same cloud-init values.

No, that's not indeed how should work. Hostnames can be set by hypervisors and we source from them correctly, and cloud-init templating allows to create custom hostnames. 

We have an immutable setup, and this is a choice by design to have all the configuration cloud-init driven.

**Comment by mudler** [comment]
It's way much better to have one single source of truth, while instead of having to deal with multiple ways of configuring things.  IF you really want to set the hostname via command line, you can also have a `runcmd` step in the cloud-init.

Besides manually changing hostname is breaking so many other flows

**Comment by ldevulder** [comment]
So how could I add hostname for my servers in the same `MachineRegistrations` yaml template in Rancher(UI)?

**Comment by mudler** [comment]
> So how could I add hostname for my servers in the same `MachineRegistrations` yaml template in Rancher(UI)?

the `MachineRegistration` takes a cloud-init configuration freeform https://rancher.github.io/os2/operator/#machineregistration that is executed on boot on each node afterward because it is merged and installed in your nodes. Any cloud init instruction that is set there should persist in the node. 

Note this might not be completely functional due to bugs like #24 , I didn't explored if such bug surfaces from that area too.

**Comment by ldevulder** [comment]
> Any cloud init instruction that is set there should persist in the node.

But as there is only one `MachineRegistration` template, we can't install more than one node in that case? I mean if the hostname is set in this template.

**Comment by mudler** [comment]
> > Any cloud init instruction that is set there should persist in the node.
> 
> But as there is only one `MachineRegistration` template, we can't install more than one node in that case? I mean if the hostname is set in this template.

I don't think there is such a limitation, but if there is, it would defeat the purpose of having `MachineRegistration`. They are meant to register machines with the same setup.

**Comment by ldevulder** [comment]
The generated ISO image I used (see internal Confluence doc) is linked with the token to a `MachineRegistration` template. So in that case I need a different ISO image for each server if I want/have to use multiple `MachineRegistration` template.
But as there are a `MachineInventories` for each server, it might be maybe easier to use this for this kind of specific configuration, no?

**Comment by mudler** [comment]
@ldevulder IF the problem is "how to specify different hostnames for all my machines without being explicit" see https://github.com/rancher-sandbox/os2/issues/18#issuecomment-1039126376 . Altought might need tweaking as it is not tested on a baremetals and such.

**Comment by ldevulder** [comment]
@mudler In that case I didn't understood your comment https://github.com/rancher-sandbox/os2/issues/35#issuecomment-1057847096. I want to use the same `MachineRegistration` template to provision mutilple node with a unique hostname for each, but if I have to set the hostname in the `cloudConfig` part in that template how can I have different hostname?

**Comment by mudler** [comment]
> @mudler In that case I didn't understood your comment [#35 (comment)](https://github.com/rancher-sandbox/os2/issues/35#issuecomment-1057847096). I want to use the same `MachineRegistration` template to provision mutilple node with a unique hostname for each, but if I have to set the hostname in the `cloudConfig` part in that template how can I have different hostname?
> 
> **EDIT:** I will try what you just post above, thanks :-)

note those examples are not tested, while the templating functionality is, so the solution might be among those lines, I didn't played with it. The sprig examples of mine might not work as I might have did some mistake there, so take it with caution. You can test it separately standalone with the `yip` tool if you want https://github.com/mudler/yip#node-data-interpolation (which elemental is sharing same libset)

**Comment by mudler** [comment]
If you manage to have dynamically/fixed on reboot, would be nice to have a nice working example that we can have in our docs! :)

**Comment by ldevulder** [comment]
I tried this config to generate a partially random hostname:
```
spec:
  cloudConfig:
    hostname: ros-node-{{ randAlphaNum 4 | nospace }}
    [ ... ]
```

It works but the hostname is regenerated upon each reboot, so I tried to add `preserve_hostname: true` but this has no effect... I'm still looking for a workaround, maybe "simply" modifying `99_custom.yaml` after the first boot to set a fixed hostname is a workaround? But more a dirty one TBH.

**Comment by mudler** [comment]
> I tried this config to generate a partially random hostname:
> 
> ```
> spec:
>   cloudConfig:
>     hostname: ros-node-{{ randAlphaNum 4 | nospace }}
>     [ ... ]
> ```

You can't rely on random strings here, you need to bake it up from something fixed in the machine. That's why the example in https://github.com/rancher-sandbox/os2/issues/18#issuecomment-1039126376 takes advantage of the machine UUID and MachineID, which is fixed. The [cloud init templating mechanisms](https://github.com/mudler/yip/blob/1d415391cc37e353facdbc7e5beb22024ca818ba/pkg/plugins/hostname.go#L36) returns the machine UUID as `{{.Values.UUID}}`, among other values that can be used for that purpose.

**Comment by ldevulder** [comment]
> returns the machine id as `{{.Values.MachineID}}`

Maybe there is an issue here, as I tried this morning and it doesn't work...



> You have also have available values from sysinfo

I will have a look at this tomorrow, thanks.

**Comment by mudler** [comment]
> > returns the machine id as `{{.Values.MachineID}}`
> 
> Maybe there is an issue here, as I tried this morning and it doesn't work...
> 
> > You have also have available values from sysinfo
> 
> I will have a look at this tomorrow, thanks.

thanks! please keep us in the loop, if something is broken in templating should be addressed, as all of this is there exactly to allow this kind of automated setup scenarios covering the maintenance aspects as well (prefixed hostnames, trace back machines from templates, ..)

**Comment by ldevulder** [comment]
I found the good syntax, it's:
```
hostname: ros-node-{{ trunc 4 . MachineID }}
```

I used `{{ .Values.MachineID }}` as all docs showed this syntax, but this morning a finally decided to test all possible syntaxes :D

I will update our internal doc with this example.

**Comment by mudler** [comment]
> 
> I will update our internal doc with this example.

This needs to be documented as well in our projects. It's not something restricted to os2 - the same setting would work for harvester, for example.
