### ISSUE TITLE
Consume framework images in the generated chart

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/os2#38]
Currently ros-operator charts are pointing to OS images, instead should point to framework images which contains only the binary and nothing else.

Since ros-operator is built statically, it should be possible to run it distroless. That would dramatically reduce download and setup times for the chart.

**Comment by Itxaka** [comment]
framework images are still too big, even with #39 

I wonder, what binaries does the ros-operator needs in the image? cause currently the whole elemental stuff is in there, including cosign at a whooping 89Mb?

As far as I can see the operator is mainly doing api stuff, so the image should not need any other binaries other than ros-operator!

Any reason why we install so many stuff in there?

**Comment by mudler** [comment]
framework image is used to overlay content from the base image, so it gets all the packages which are not part of it (so for example, openSUSE, fedora, etc). I didn't had a look at the framework images content, but I'm guessing there must be something lurking there, I'm guessing that buildx setup on runner might be not working correctly and maybe we get the full image at the end, but that's just a speculation of mine.

**Comment by mudler** [comment]
> framework images are still too big, even with #39
> 
> I wonder, what binaries does the ros-operator needs in the image? cause currently the whole elemental stuff is in there, including cosign at a whooping 89Mb?
> 
> As far as I can see the operator is mainly doing api stuff, so the image should not need any other binaries other than ros-operator!

The operator doesn't need anything, we can also do a specific image for it. I wouldn't expect anyhow the framework images to be that big. something is def. not ok. I'll compare with the cos-toolkit ones https://quay.io/repository/costoolkit/framework?tab=tags

**Comment by Itxaka** [comment]
yeah, quay is lying in the size they report. I mean, the cosign binary is already 87Mb + elemental is 16Mb and luet another 35Mb and that image already has the same problem with the /var/cache and /var/db, is still there.

Maybe they dont report the size with those dirs included? Cause locally I get:
```
quay.io/costoolkit/framework              latest                                                             d37b4ef9cd81   11 hours ago   342MB

```

**Comment by Itxaka** [comment]
And here are the sizes of the framework image from costoolkit:

```
zeus:/var/lib/docker/btrfs/subvolumes/26f100512e553b57593771ee607de196394fe8013a49f570fe1686b894a94717 # du -chs *
56K	etc
28K	lib
165M	usr
164M	var
328M	total
```

So its mostly the /var dir with the leftovers from luet the ones filling up the image. Not sure where quay is getting the image size, maybe its compressed somehow...

**Comment by Itxaka** [comment]
Closed as part of https://github.com/rancher-sandbox/os2/pull/40 instead of the framework image, we got the ros-operator image which just contains the ros-operator binary.
