### ISSUE TITLE
Auto-installing ISO should not show `localhost login:` prompt

### ISSUE THREAD

**Issue by jsundqvist** [rancher-sandbox/os2#52]
When using an ISO that was created with a config.yaml, it's boots just as the regular ISO, showing the login prompt suggesting login using root:ros. Then, after about 50 seconds of secretly finishing the installation, it reboots from the harddrive. This works, obviously, but is very confusing.

I would expect the auto-installing ISO to _not_ show the login prompt, as this allows users to unknowingly interfere with the installation, and instead show the logs of what the installer is doing.

**Comment by kkaempf** [comment]
We need means to interact with the system in case of problems. Not sure show to do this without a login.

**Comment by jsundqvist** [comment]
Sure, good point. I was not getting any log output after the login prompt because my config was missing `rancherd.role`. My main concern was the apparent lack of log output, not the actual prompt, so will close this one.
