### ISSUE TITLE
Support container images as installation bootstrap

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/os2#6]
See: https://github.com/rancher/os2/issues/8

https://github.com/rancher-sandbox/os2/blob/7741733950e35fea2ad3b30ab6290fcd16e61753/pkg/config/read.go#L209 needs to support container images, see configuration test for elemental-cli which is relevant for the purpose: https://github.com/rancher-sandbox/os2/blob/master/pkg/config/read_test.go#L118 (the test checks how the config of os2 is translated to env var that will be used during the elemental installation process)

ping @mudler

**Comment by Itxaka** [comment]
done on https://github.com/rancher-sandbox/os2/pull/32
