### ISSUE TITLE
Split ros-operator into its own repo

### ISSUE THREAD

**Issue by Itxaka** [rancher-sandbox/os2#67]
It makes no sense to have all this mixed together with the os2 files. First, everything is clumped into a ton of files to setup like the CI, the makefile, the scripts, etc... while ros-operator is very simple and could do with a simple repo in which we control everything and its much clearer where to change things.

Plus we can release it separately instead of in a big release with the installer, the chart, the iso, etc..

ros-operator and its chart should live in its own repo for ease of releasing, testing and updating. We also dont need os2 to test the ros-operator so that makes it simpler.

A test repo is available at https://github.com/Itxaka/ros-operator with the full package, CI stuff, release stuff. 

## Action items
- [x] Split the operator code to https://github.com/rancher-sandbox/rancheros-operator with all the pipelines, tests, etc.
- [x] Test releasing and QA 
- [x] Update os2 to drop the ros-operator code counterpart (adapt pipelines and CI accordingly)

**Comment by Itxaka** [comment]
@mudler what do you mean by QA? like the artifacts are there so it can be reproduced or something else?

**Comment by mudler** [comment]
yup just some sanity checking if things are still working as expected (e.g. the correct default repos in the default chart values file, and such)

**Comment by Itxaka** [comment]
I mean, the integration tests should check that automatically no? As we are pushing the image and building the chart based on that image tag, that means that when we test it afterwards by using that chart it needs to pull the correct image. I will still manually check just in case :D

**Comment by mudler** [comment]
you never know :D I did find out later that it was using the wrong image once.. :dancers:

**Comment by Itxaka** [comment]
Tested on https://github.com/rancher-sandbox/rancheros-operator/actions/runs/2033704156

Get inside the helm chart Chart.yaml: 

```
appVersion: v0.0.0-5ff94bf
```

And inside the helm chart Values.yaml:

```
image:
  empty: rancher/pause:3.1
  repository: quay.io/costoolkit/ros-operator-ci
  tag: v0.0.0-5ff94bf
  imagePullPolicy: IfNotPresent
```

which both correspond to the commit:

`  HEAD is now at 5ff94bf Merge 005df2f7f2b31cf5acfd884c27a1c67ce6cfa563 into f93860d4bac9982e2733f2d3f35b9f3f68f6272`

So the QA part should be ok. Testing the label once is merged...

**Comment by Itxaka** [comment]
ah no, missing the `v` :/

**Comment by Itxaka** [comment]
installing the chart from the published repo works as expected, the rancheros-operator is up and running

```
$ helm install rancheros/rancheros-operator --generate-name --devel 
NAME: rancheros-operator-1648202552
LAST DEPLOYED: Fri Mar 25 11:02:33 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
{}
```

```
$ kubectl describe pod rancheros-operator-5c5d676f8d-hgs8h
Name:         rancheros-operator-5c5d676f8d-hgs8h
Namespace:    default
Priority:     0
Node:         kind-control-plane/172.18.0.2
Start Time:   Fri, 25 Mar 2022 11:02:34 +0100
Labels:       app=rancheros-operator
              pod-template-hash=5c5d676f8d
Annotations:  <none>
Status:       Running
IP:           10.244.0.18
IPs:
  IP:           10.244.0.18
Controlled By:  ReplicaSet/rancheros-operator-5c5d676f8d
Containers:
  rancheros-operator:
    Container ID:  containerd://79e5447ea1642c59f96d7871cdb52bd172529984dbde33808af5de584ab8ceb2
    Image:         quay.io/costoolkit/rancheros-operator-ci:v0.1.0-alpha1-785899e
    Image ID:      quay.io/costoolkit/rancheros-operator-ci@sha256:d0cc8b0264cc4a8020b9b17b73442941cdd8ad55cb4100900d223bc707b1ac03
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/sbin/rancheros-operator
    State:          Running
      Started:      Fri, 25 Mar 2022 11:02:39 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from rancheros-operator-token-7q682 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  rancheros-operator-token-7q682:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rancheros-operator-token-7q682
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     cattle.io/os=linux:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  2m53s  default-scheduler  Successfully assigned default/rancheros-operator-5c5d676f8d-hgs8h to kind-control-plane
  Normal  Pulling    2m52s  kubelet            Pulling image "quay.io/costoolkit/rancheros-operator-ci:v0.1.0-alpha1-785899e"
  Normal  Pulled     2m48s  kubelet            Successfully pulled image "quay.io/costoolkit/rancheros-operator-ci:v0.1.0-alpha1-785899e" in 3.838169221s
  Normal  Created    2m48s  kubelet            Created container rancheros-operator
  Normal  Started    2m48s  kubelet            Started container rancheros-operator
```

**Comment by Itxaka** [comment]
umm...any idea why the annotations would be missing in the pod @mudler ?

The chart is correct and has all the annotations in there..

**Comment by Itxaka** [comment]
oh I guess this is for the chart only, so rancher can do stuff with it as part of their chart catalog I guess..

**Comment by Itxaka** [comment]
done, will create a couple of follow up cards for chart url/version config
