### ISSUE TITLE
e2e upgrade tests

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/os2#86]
Currently our e2e tests are leveraging API-kind of tests, but with no real node attached. This prevents us to test things like upgrades, or specific scenarios where we inject custom node configuration.

This card is about to set-up in parallel a VM or something which mocks a os2 node and can join e2e tests for a simple upgrade scenario that can also be run locally while iterating during development.

**Comment by ldevulder** [comment]
Is it the same as this issue: https://github.com/rancher-sandbox/os2/issues/42 ?
