### ISSUE TITLE
Arm64 arch build is commented

### ISSUE THREAD

**Issue by mazzy89** [rancher-sandbox/os2#92]
By looking at the `.drone.yml` file, the Arm64 build is commented. It was added by @ibuildthecloud almost 
six months ago, but it's not clear the reasons why it is not used at the moment. It is maybe an untested build or perhaps a non-working build? As a user of the now-deceased k3os, I would like to use the RancherOS v2 for my RPIs. 

Would you need any help with testing it out? 

OT: This message should have been more appropriate for a Slack channel, but it seems I cannot access the Slack workspace `rancher-users` w/o an invitation.

**Comment by kkaempf** [comment]
drone is for continuous rebuilds and replaced by github actions currently.

We certainly would welcome help for ARM support. We just don't know where to begin :-/

Btw, I sent you an invite to rancher-users Slack :wink:

**Comment by kkaempf** [comment]
Closing for now since we don't use drone currently.

**Comment by mazzy89** [comment]
Thanks, @kkaempf, for the fast reaction, and thanks for the invitation.

**Comment by mudler** [comment]
Also you might be interested in https://github.com/rancher-sandbox/cOS-toolkit/issues/1138 as it is directly related to the subject

**Comment by mazzy89** [comment]
Grazie @mudler 😉

Any reasons why os2 is under two different orgs? For the arm64 support where the discussions should go on, https://github.com/rancher/os2/issues/16 or under the rander-sandbox gh org?

**Comment by Itxaka** [comment]
@mazzy89 rancher-sandbox is the most current up to date, so discussions should go under there. There is currently a card for arm support for os2 but somehow is under cos-toolkit. Bit of a mess currently :) https://github.com/rancher-sandbox/cOS-toolkit/issues/1138
